#!/usr/bin/env bash
set -euo pipefail

echo "Applying Restaurant Clocking delivery patch 01..."

# Run this from the Django project root: ~/restaurant_clocking
if [ ! -f manage.py ] || [ ! -d core ] || [ ! -d templates ]; then
  echo "ERROR: Run this script from the Django project root, e.g. cd ~/restaurant_clocking"
  exit 1
fi

stamp=$(date +%Y%m%d_%H%M%S)
mkdir -p backups_patch_01_$stamp
cp core/models.py core/views.py core/urls.py templates/payroll_problems.html templates/weekly_summary.html backups_patch_01_$stamp/ 2>/dev/null || true

python3 - <<'PY'
from pathlib import Path

# 1) Add notes field to ClockEvent and keep clock_type long enough for break events.
models = Path('core/models.py')
s = models.read_text()
s = s.replace("clock_type = models.CharField(max_length=3, choices=CLOCK_TYPES)", "clock_type = models.CharField(max_length=20, choices=CLOCK_TYPES)")
if "notes = models.TextField" not in s:
    s = s.replace("    method = models.CharField(max_length=20, default='QR')\n", "    method = models.CharField(max_length=20, default='QR')\n    notes = models.TextField(blank=True, default='')\n")
models.write_text(s)

# 2) Add URL for row-level correction page.
urls = Path('core/urls.py')
u = urls.read_text()
if "manager_fix_day" not in u.split("urlpatterns")[0]:
    u = u.replace("    manager_add_missing_event,\n", "    manager_add_missing_event,\n    manager_fix_day,\n")
if "manager/fix-day/" not in u:
    u = u.replace("    path('manager/add-missing-event/', manager_add_missing_event, name='manager_add_missing_event'),\n", "    path('manager/add-missing-event/', manager_add_missing_event, name='manager_add_missing_event'),\n    path('manager/fix-day/', manager_fix_day, name='manager_fix_day'),\n")
urls.write_text(u)
PY

# 3) Migration. Safe to commit. If your DB already has the columns, Django will no-op after migrate state is applied.
mkdir -p core/migrations
cat > core/migrations/0003_clockevent_notes_and_type_len.py <<'PY'
# Generated by delivery patch 01
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rostershift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockevent',
            name='clock_type',
            field=models.CharField(choices=[('IN', 'Clock In'), ('BREAK_START', 'Break Start'), ('BREAK_END', 'Break End'), ('OUT', 'Clock Out')], max_length=20),
        ),
        migrations.AddField(
            model_name='clockevent',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
PY

# 4) Replace Payroll Problems page: add Fix/Edit button beside each problem and remove Add Missing Event as the main action.
cat > templates/payroll_problems.html <<'HTML'
<!DOCTYPE html>
<html>
<head>
    <title>Payroll Problems</title>
    <style>
        body { font-family: Arial, sans-serif; background: #f4f6f8; margin: 0; padding: 25px; color: #222; }
        .container { max-width: 1250px; margin: auto; background: white; padding: 24px; border-radius: 14px; border: 1px solid #e5e7eb; }
        table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        th, td { border-bottom: 1px solid #e5e7eb; padding: 10px; text-align: left; vertical-align: top; }
        th { background: #f9fafb; }
        .warn { color: #b42318; font-weight: bold; }
        .ok { color: #1a7f37; font-weight: bold; }
        .button { display: inline-block; padding: 10px 13px; background: #2563eb; color: white; text-decoration: none; border-radius: 8px; font-weight: bold; margin-right: 8px; }
        .secondary { background: #4b5563; }
        .fix { background: #b45309; }
        input, button { padding: 8px; }
        .note { background: #fffbeb; border-left: 4px solid #f59e0b; padding: 10px; margin: 12px 0; }
    </style>
</head>
<body>
<div class="container">
<h1>Payroll Problems</h1>
<p>Review and fix missing clock-outs, unended breaks, unusual shifts and urgent issues before payroll export.</p>

<form method="get">
    Week Start: <input type="date" name="week_start" value="{{ week_start|date:'Y-m-d' }}">
    <button type="submit">View Week</button>
</form>

<h2>{{ week_start }} to {{ week_end }}</h2>

{% if problem_count == 0 %}
    <p class="ok">No payroll problems found for this week.</p>
{% else %}
    <div class="note"><strong>{{ problem_count }} problem(s) found.</strong> Fix or review these before exporting payroll. Each row has a Fix/Edit button for that employee and date.</div>
{% endif %}

<table>
    <tr>
        <th>Date</th><th>Employee</th><th>Roster</th><th>Status</th><th>Worked</th><th>Break</th><th>Problem</th><th>Action</th>
    </tr>
    {% for row in rows %}
    <tr>
        <td>{{ row.date }}</td>
        <td>{{ row.employee }}</td>
        <td>{{ row.roster }}</td>
        <td>{{ row.status }}</td>
        <td>{{ row.worked_hours }}</td>
        <td>{{ row.break_minutes }} mins</td>
        <td class="warn">{{ row.problem }}</td>
        <td>
            <a class="button fix" href="/manager/fix-day/?employee_number={{ row.employee_number }}&event_date={{ row.date|date:'Y-m-d' }}&week_start={{ week_start|date:'Y-m-d' }}">Fix / Edit</a>
        </td>
    </tr>
    {% empty %}
    <tr><td colspan="8" class="ok">No problems found.</td></tr>
    {% endfor %}
</table>

<p>
    <a class="button" href="/manager/weekly-summary/?week_start={{ week_start|date:'Y-m-d' }}">Weekly Summary</a>
    <a class="button secondary" href="/manager/today/">Today's Dashboard</a>
    <a class="button secondary" href="/">Home</a>
</p>
</div>
</body>
</html>
HTML

# 5) New row-level correction page. Manager sees exact day/event list, can add missing event or delete mistaken event.
cat > templates/manager_fix_day.html <<'HTML'
<!DOCTYPE html>
<html>
<head>
    <title>Fix Clock Day</title>
    <style>
        body { font-family: Arial, sans-serif; background: #f4f6f8; margin: 0; padding: 25px; color: #222; }
        .container { max-width: 1050px; margin: auto; background: white; padding: 24px; border-radius: 14px; border: 1px solid #e5e7eb; }
        table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        th, td { border-bottom: 1px solid #e5e7eb; padding: 10px; text-align: left; }
        th { background: #f9fafb; }
        .button, button { display: inline-block; padding: 10px 13px; background: #2563eb; color: white; text-decoration: none; border: none; border-radius: 8px; font-weight: bold; margin-right: 8px; cursor: pointer; }
        .danger { background: #b42318; }
        .secondary { background: #4b5563; }
        .ok { color: #1a7f37; font-weight: bold; }
        .warn { color: #b42318; font-weight: bold; }
        input, select, textarea { padding: 9px; width: 100%; max-width: 360px; box-sizing: border-box; }
        textarea { max-width: 650px; height: 70px; }
        .grid { display: grid; grid-template-columns: repeat(2, minmax(240px, 1fr)); gap: 14px; }
        .card { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 12px; padding: 16px; margin: 14px 0; }
        .note { background: #fffbeb; border-left: 4px solid #f59e0b; padding: 10px; margin: 12px 0; }
    </style>
</head>
<body>
<div class="container">
<h1>Fix / Edit Clocking Day</h1>

{% if message %}<p class="ok">{{ message }}</p>{% endif %}
{% if error %}<p class="warn">{{ error }}</p>{% endif %}

<p><strong>Employee:</strong> {{ employee.name }} ({{ employee.employee_number }})</p>
<p><strong>Date:</strong> {{ event_date }}</p>

<div class="card">
    <h2>Current calculated result</h2>
    <p><strong>Status:</strong> {{ day.status }}</p>
    <p><strong>Roster:</strong> {{ day.roster }}</p>
    <p><strong>Worked:</strong> {{ day.worked_hours }} hours</p>
    <p><strong>Break:</strong> {{ day.break_minutes }} mins</p>
    <p><strong>Issue:</strong> {% if day.issue == 'OK' %}<span class="ok">OK</span>{% else %}<span class="warn">{{ day.issue }}</span>{% endif %}</p>
</div>

<div class="note">
    Use this page to correct the day, not just to add random events. After adding or deleting an event, the calculated result above should make sense before payroll is exported.
</div>

<h2>Events on this day</h2>
<table>
    <tr><th>Time</th><th>Type</th><th>Method</th><th>Notes</th><th>Action</th></tr>
    {% for event in events %}
    <tr>
        <td>{{ event.local_time }}</td>
        <td>{{ event.get_clock_type_display }}</td>
        <td>{{ event.method }}</td>
        <td>{{ event.notes }}</td>
        <td>
            <form method="post" onsubmit="return confirm('Delete this event? This should only be used to correct mistakes.');">
                {% csrf_token %}
                <input type="hidden" name="mode" value="delete">
                <input type="hidden" name="event_id" value="{{ event.id }}">
                <button class="danger" type="submit">Delete</button>
            </form>
        </td>
    </tr>
    {% empty %}
    <tr><td colspan="5">No clock events recorded for this day.</td></tr>
    {% endfor %}
</table>

<div class="card">
<h2>Add missing event</h2>
<form method="post">
    {% csrf_token %}
    <input type="hidden" name="mode" value="add">
    <div class="grid">
        <div>
            <label>Event type</label><br>
            <select name="clock_type" required>
                <option value="IN">Clock In</option>
                <option value="BREAK_START">Start Break</option>
                <option value="BREAK_END">End Break</option>
                <option value="OUT">Clock Out</option>
            </select>
        </div>
        <div>
            <label>Time</label><br>
            <input type="time" name="event_time" required>
        </div>
    </div>
    <p>
        <label>Reason for correction</label><br>
        <textarea name="reason" required placeholder="Example: employee forgot to clock out; manager confirmed finish time was 22:15"></textarea>
    </p>
    <button type="submit">Add Event</button>
</form>
</div>

<p>
    <a class="button secondary" href="/manager/payroll-problems/?week_start={{ week_start|date:'Y-m-d' }}">Back to Payroll Problems</a>
    <a class="button secondary" href="/manager/weekly-summary/?week_start={{ week_start|date:'Y-m-d' }}">Weekly Summary</a>
    <a class="button secondary" href="/manager/today/">Today's Dashboard</a>
</p>
</div>
</body>
</html>
HTML

# 6) Append improved views. These override earlier same-named functions when Django imports the module.
cat >> core/views.py <<'PY'

# -------------------------------------------------------------------
# Delivery patch 01: row-level payroll corrections + safer payroll export
# -------------------------------------------------------------------

from django.contrib.auth.decorators import login_required as _patch_login_required
from django.shortcuts import get_object_or_404 as _patch_get_object_or_404
from django.http import HttpResponseRedirect as _patch_HttpResponseRedirect
from core.compliance import calculate_employee_day as _patch_calculate_employee_day
from core.compliance import get_week_rows as _patch_get_week_rows


def _patch_current_week_start():
    today = timezone.localdate()
    return today - timedelta(days=today.weekday())


def _patch_parse_week_start(request):
    raw = request.GET.get("week_start") or request.POST.get("week_start")
    if raw:
        return datetime.strptime(raw, "%Y-%m-%d").date()
    return _patch_current_week_start()


@_patch_login_required
def manager_fix_day(request):
    emp_no = request.GET.get("employee_number") or request.POST.get("employee_number")
    date_raw = request.GET.get("event_date") or request.POST.get("event_date")
    week_start = _patch_parse_week_start(request)

    if not emp_no or not date_raw:
        return render(request, "manager_fix_day.html", {
            "error": "Missing employee number or date.",
            "employee": None,
            "event_date": None,
            "events": [],
            "day": {},
            "week_start": week_start,
        })

    employee = _patch_get_object_or_404(Employee, employee_number=emp_no)
    event_date = datetime.strptime(date_raw, "%Y-%m-%d").date()
    message = ""
    error = ""

    if request.method == "POST":
        mode = request.POST.get("mode")

        if mode == "add":
            clock_type = request.POST.get("clock_type")
            event_time = request.POST.get("event_time")
            reason = (request.POST.get("reason") or "").strip()

            if clock_type not in ["IN", "BREAK_START", "BREAK_END", "OUT"]:
                error = "Invalid event type."
            elif not reason:
                error = "A correction reason is required."
            else:
                naive_dt = datetime.strptime(f"{event_date} {event_time}", "%Y-%m-%d %H:%M")
                event_dt = timezone.make_aware(naive_dt)
                ClockEvent.objects.create(
                    employee=employee,
                    clock_type=clock_type,
                    timestamp=event_dt,
                    method="MANAGER",
                    notes=f"Manager correction: {reason}",
                )
                message = f"Added {clock_type} for {employee.name} at {event_time}."

        elif mode == "delete":
            event_id = request.POST.get("event_id")
            event = _patch_get_object_or_404(ClockEvent, id=event_id, employee=employee, timestamp__date=event_date)
            old = f"{timezone.localtime(event.timestamp).strftime('%H:%M')} {event.clock_type}"
            event.delete()
            message = f"Deleted event: {old}."

    events = list(ClockEvent.objects.filter(employee=employee, timestamp__date=event_date).order_by("timestamp"))
    for event in events:
        event.local_time = timezone.localtime(event.timestamp).strftime("H:%M").replace("H", "%H") if False else timezone.localtime(event.timestamp).strftime("%H:%M")

    day = _patch_calculate_employee_day(employee, event_date, include_live=True)

    return render(request, "manager_fix_day.html", {
        "employee": employee,
        "event_date": event_date,
        "events": events,
        "day": day,
        "message": message,
        "error": error,
        "week_start": week_start,
    })


@_patch_login_required
def payroll_problems(request):
    week_start = _patch_parse_week_start(request)
    week_end = week_start + timedelta(days=6)
    rows = []

    for employee in Employee.objects.filter(active=True).order_by("name"):
        for i in range(7):
            day = week_start + timedelta(days=i)
            d = _patch_calculate_employee_day(employee, day, include_live=True)
            problems = []

            if d.get("missing_clock_out"):
                problems.append("Missing clock-out")
            if d.get("invalid_sequence"):
                problems.append("Check clock sequence")
            if d.get("is_urgent"):
                problems.append(d.get("issue"))
            if d.get("worked_hours", 0) > 12:
                problems.append("Unusually long shift")

            if problems:
                rows.append({
                    "date": day,
                    "employee_number": employee.employee_number,
                    "employee": employee.name,
                    "roster": d.get("roster"),
                    "status": d.get("status"),
                    "worked_hours": d.get("worked_hours"),
                    "break_minutes": d.get("break_minutes"),
                    "problem": "; ".join(sorted(set([p for p in problems if p]))),
                })

    return render(request, "payroll_problems.html", {
        "week_start": week_start,
        "week_end": week_end,
        "rows": rows,
        "problem_count": len(rows),
    })


@_patch_login_required
def manager_weekly_summary(request):
    week_start = _patch_parse_week_start(request)
    week_end = week_start + timedelta(days=6)
    standard_hours = float(request.GET.get("standard_hours", "39"))
    summary_rows = _patch_get_week_rows(week_start, standard_hours)

    unresolved = [row for row in summary_rows if row.get("warning") != "OK"]

    return render(request, "weekly_summary.html", {
        "week_start": week_start,
        "week_end": week_end,
        "summary_rows": summary_rows,
        "standard_hours": standard_hours,
        "unresolved_problem_count": len(unresolved),
    })


@_patch_login_required
def export_sage_payroll_csv(request):
    week_start = _patch_parse_week_start(request)
    period_number = request.GET.get("period", "1")
    standard_hours = float(request.GET.get("standard_hours", "39"))
    include_header = request.GET.get("include_header") == "1"
    rows = _patch_get_week_rows(week_start, standard_hours)

    response = HttpResponse(content_type="text/csv")
    response["Content-Disposition"] = 'attachment; filename="sage_payroll_export.csv"'
    writer = csv.writer(response)

    # Sage Payroll IE single-timesheet import order:
    # period number, employee number, 0000, payment element 1, payment element 2, payment element 3.
    # Header is OFF by default because Sage imports usually expect raw rows only.
    if include_header:
        writer.writerow(["PeriodNumber", "EmployeeNumber", "0000", "NormalHours", "SundayHours", "OvertimeHours"])

    for row in rows:
        if row["paid_minutes"] == 0:
            continue
        writer.writerow([
            period_number,
            row["employee_number"],
            "0000",
            row["normal_hours"],
            row["sunday_hours"],
            row["overtime_hours"],
        ])

    return response
PY

# 7) Weekly summary warning and Sage export controls.
python3 - <<'PY'
from pathlib import Path
p = Path('templates/weekly_summary.html')
s = p.read_text()
if "unresolved_problem_count" not in s:
    s = s.replace("<h2>{{ week_start }} to {{ week_end }}</h2>", """<h2>{{ week_start }} to {{ week_end }}</h2>

{% if unresolved_problem_count and unresolved_problem_count > 0 %}
<div style=\"background:#fffbeb; border-left:4px solid #f59e0b; padding:12px; margin:12px 0;\">
    <strong>{{ unresolved_problem_count }} payroll warning(s) found.</strong>
    Review Payroll Problems before exporting to Sage.
    <a href=\"/manager/payroll-problems/?week_start={{ week_start|date:'Y-m-d' }}\">Open Payroll Problems</a>
</div>
{% endif %}
""")
# Change export button text to mention Sage raw CSV
s = s.replace("Download Sage Payroll CSV", "Download Sage Payroll CSV")
# Add payroll problems button if missing
if "/manager/payroll-problems/" not in s.split("<p>")[-1]:
    s = s.replace("<a class=\"button secondary\" href=\"/manager/today/\">Today's Dashboard</a>", "<a class=\"button secondary\" href=\"/manager/payroll-problems/?week_start={{ week_start|date:'Y-m-d' }}\">Payroll Problems</a>\n    <a class=\"button secondary\" href=\"/manager/today/\">Today's Dashboard</a>")
p.write_text(s)
PY

# 8) Set Irish timezone if still UTC.
python3 - <<'PY'
from pathlib import Path
p = Path('config/settings.py')
s = p.read_text()
s = s.replace("TIME_ZONE = 'UTC'", "TIME_ZONE = 'Europe/Dublin'")
p.write_text(s)
PY

echo "Patch applied. Now run:"
echo "  python manage.py migrate"
echo "  python manage.py check"
echo "  python manage.py runserver 0.0.0.0:8000"
echo ""
echo "Then test: /manager/payroll-problems/ -> Fix/Edit beside a problem -> add/delete event -> Weekly Summary -> Sage export."
