# Generated by delivery patch 01
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rostershift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockevent',
            name='clock_type',
            field=models.CharField(choices=[('IN', 'Clock In'), ('BREAK_START', 'Break Start'), ('BREAK_END', 'Break End'), ('OUT', 'Clock Out')], max_length=20),
        ),
        migrations.AddField(
            model_name='clockevent',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
